name: Запуск Unit Тестов

on: 
  push: 
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Установка .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Установка зависимостей
        run: dotnet restore

      - name: Сборка
        run: dotnet build --configuration Release --no-restore

      - name: Запуск тестов
        run: dotnet test --no-restore --verbosity normal
